version: '3.7'

services:
  appdb:
    image: mysql:5.7.29
    container_name: kdsp-db
    restart: always
    command: --sql_mode="" #--default-authentication-plugin=mysql_native_password
    ports:
        - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_USER="root"
        - MYSQL_PASSWORD=123456
        - MYSQL_DATABASE=KDSP
    volumes:
        - kdsp-my-db:/var/lib/mysql
  adminer:
    image: adminer:4.7.6
    container_name: adminer-db
    restart: always
    ports:
      - 8089:8080      
volumes:
  kdsp-my-db: